<?php
$names = array (
  'brand' => '品牌展示',
  'buy' => '采购清单',
  'contact' => '联系方式',
  'credit' => '诚信档案',
  'footer' => '公共页脚',
  'header' => '公共页头',
  'honor' => '荣誉资质',
  'index' => '学校首页',
  'info' => '招商代理',
  'introduce' => '学校介绍',
  'job' => '人才招聘',
  'link' => '友情链接',
  'main_brand' => '首页品牌展示',
  'main_elite' => '首页产品推荐',
  'main_info' => '首页招商代理',
  'main_introduce' => '首页学校介绍',
  'main_photo' => '首页学校相册',
  'main_sell' => '首页最新供应',
  'main_video' => '首页学校视频',
  'message' => '留言询价',
  'news' => '学校新闻',
  'photo' => '学校相册',
  'sell' => '供应产品',
  'side' => '侧栏',
  'side_announce' => '侧栏网站公告',
  'side_contact' => '侧栏联系方式',
  'side_honor' => '侧栏荣誉资质',
  'side_link' => '侧栏友情链接',
  'side_news' => '侧栏新闻中心',
  'side_page' => '侧栏单页',
  'side_search' => '侧栏站内搜索',
  'side_type' => '侧栏产品分类',
  'video' => '学校视频',
);
?>
